package su.kidoz.feature.diagram

import su.kidoz.core.model.ForeignKeyRule
import kotlin.test.Test
import kotlin.test.assertFalse
import kotlin.test.assertTrue

class DiagramDdlGeneratorTest {
    @Test
    fun `postgres ddl uses double quotes and identity columns`() {
        val table = draftTable(name = "invoice")

        val ddl =
            DiagramDdlGenerator.generate(
                tables = listOf(table),
                relationships = emptyList(),
                dialect = DiagramDdlDialect.PostgreSql,
            )

        assertTrue(ddl.contains("CREATE TABLE \"billing\".\"invoice\""))
        assertTrue(ddl.contains("\"id\" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL"))
        assertTrue(ddl.contains("\"notes\" TEXT"))
        assertTrue(ddl.contains("PRIMARY KEY (\"id\")"))
    }

    @Test
    fun `mysql ddl uses backticks auto increment and mysql defaults`() {
        val table = draftTable(name = "invoice")

        val ddl =
            DiagramDdlGenerator.generate(
                tables = listOf(table),
                relationships = emptyList(),
                dialect = DiagramDdlDialect.MySql,
            )

        assertTrue(ddl.contains("CREATE TABLE `billing`.`invoice`"))
        assertTrue(ddl.contains("`id` INT NOT NULL AUTO_INCREMENT"))
        assertTrue(ddl.contains("`notes` VARCHAR(255)"))
        assertTrue(ddl.contains("PRIMARY KEY (`id`)"))
    }

    @Test
    fun `h2 ddl uses identity columns and h2 defaults`() {
        val table = draftTable(name = "invoice")

        val ddl =
            DiagramDdlGenerator.generate(
                tables = listOf(table),
                relationships = emptyList(),
                dialect = DiagramDdlDialect.H2,
            )

        assertTrue(ddl.contains("\"id\" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL"))
        assertTrue(ddl.contains("\"notes\" VARCHAR(255)"))
    }

    @Test
    fun `mysql ddl emits supported foreign key rules`() {
        val customer = draftTable(schema = null, name = "customer")
        val order = draftTable(schema = null, name = "order")
        val relationship =
            relationship(
                source = order,
                target = customer,
                deleteRule = ForeignKeyRule.SET_NULL,
            )

        val ddl =
            DiagramDdlGenerator.generate(
                tables = listOf(customer, order),
                relationships = listOf(relationship),
                dialect = DiagramDdlDialect.MySql,
            )

        assertTrue(ddl.contains("ALTER TABLE `order` ADD CONSTRAINT `fk_order_customer`"))
        assertTrue(ddl.contains("FOREIGN KEY (`customer_id`) REFERENCES `customer` (`id`) ON DELETE SET NULL"))
    }

    @Test
    fun `sqlite ddl uses inline primary and foreign keys`() {
        val customer = draftTable(schema = null, name = "customer")
        val order = draftTable(schema = null, name = "order")
        val relationship =
            relationship(
                source = order,
                target = customer,
                deleteRule = ForeignKeyRule.CASCADE,
            )

        val ddl =
            DiagramDdlGenerator.generate(
                tables = listOf(customer, order),
                relationships = listOf(relationship),
                dialect = DiagramDdlDialect.Sqlite,
            )

        assertTrue(ddl.contains("\"id\" INTEGER PRIMARY KEY AUTOINCREMENT"))
        assertTrue(ddl.contains("CONSTRAINT \"fk_order_customer\""))
        assertTrue(ddl.contains("FOREIGN KEY (\"customer_id\") REFERENCES \"customer\" (\"id\") ON DELETE CASCADE"))
        assertFalse(ddl.contains("ALTER TABLE"))
    }

    private fun draftTable(
        schema: String? = "billing",
        name: String,
    ): DiagramTable =
        DiagramTable(
            id = "${schema.orEmpty()}.$name",
            name = name,
            schema = schema,
            x = 0f,
            y = 0f,
            columns =
                listOf(
                    DiagramColumn(
                        id = "$name:id",
                        name = "id",
                        type = "INTEGER",
                        nullable = false,
                        isPrimaryKey = true,
                        autoIncrement = true,
                        isDraft = true,
                    ),
                    DiagramColumn(
                        id = "$name:notes",
                        name = "notes",
                        type = "",
                        nullable = true,
                        isDraft = true,
                    ),
                    DiagramColumn(
                        id = "$name:customer_id",
                        name = "customer_id",
                        type = "INTEGER",
                        nullable = true,
                        isDraft = true,
                    ),
                ),
            isDraft = true,
        )

    private fun relationship(
        source: DiagramTable,
        target: DiagramTable,
        deleteRule: ForeignKeyRule,
    ): DiagramRelationship =
        DiagramRelationship(
            id = "${source.id}->${target.id}",
            name = "fk_${source.name}_${target.name}",
            sourceTableId = source.id,
            sourceColumns = listOf("customer_id"),
            targetTableId = target.id,
            targetColumns = listOf("id"),
            deleteRule = deleteRule,
            isDraft = true,
        )
}
